"""Update ApprovementLog

Revision ID: 2ff551175148
Revises: 4a323d946bda
Create Date: 2014-11-20 09:58:54.365035

"""

# revision identifiers, used by Alembic.
revision = '2ff551175148'
down_revision = '4a323d946bda'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvement_log', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('approvement_log', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('approvement_log', 'approved_at')
    op.drop_column('approvement_log', 'is_approved')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvement_log', sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('approvement_log', sa.Column('approved_at', mysql.DATETIME(), nullable=True))
    op.drop_column('approvement_log', 'updated_at')
    op.drop_column('approvement_log', 'status')
    ### end Alembic commands ###
