"""Add bad feed to Blog.

Revision ID: 50c7b3046a29
Revises: 551836ef6543
Create Date: 2014-11-29 12:42:06.043935

"""

# revision identifiers, used by Alembic.
revision = '50c7b3046a29'
down_revision = '551836ef6543'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('bad_feed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'bad_feed')
    ### end Alembic commands ###
