"""Add feed_timezone_offset to Blog model.

Revision ID: edc160b5335
Revises: 247470cfb66f
Create Date: 2014-11-28 19:23:50.276249

"""

# revision identifiers, used by Alembic.
revision = 'edc160b5335'
down_revision = '247470cfb66f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('feed_timezone_offset', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'feed_timezone_offset')
    ### end Alembic commands ###
