"""Add clicks to Post model.

Revision ID: 4970efabc64a
Revises: 46b93a07c5cc
Create Date: 2014-11-26 14:49:47.287545

"""

# revision identifiers, used by Alembic.
revision = '4970efabc64a'
down_revision = '46b93a07c5cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
