"""Add Kind model.

Revision ID: 247470cfb66f
Revises: 5223d07f2efe
Create Date: 2014-11-28 19:20:14.883619

"""

# revision identifiers, used by Alembic.
revision = '247470cfb66f'
down_revision = '5223d07f2efe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['kind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kind')
    ### end Alembic commands ###
