"""Add has spider to Blog.

Revision ID: 20892eac89e5
Revises: 2ff551175148
Create Date: 2014-11-20 19:26:37.462308

"""

# revision identifiers, used by Alembic.
revision = '20892eac89e5'
down_revision = '2ff551175148'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('has_spider', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'has_spider')
    ### end Alembic commands ###
