"""Add RecommendPost.

Revision ID: 3687ce6a0924
Revises: 4da6f7fc0881
Create Date: 2014-11-26 11:24:06.693535

"""

# revision identifiers, used by Alembic.
revision = '3687ce6a0924'
down_revision = '4da6f7fc0881'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('keywords', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'post', 'keywords')
    op.drop_table('recommend_post')
    ### end Alembic commands ###
