"""Add published_at to post

Revision ID: 1c915a042c5f
Revises: 35e5c528d70f
Create Date: 2014-11-06 22:32:53.172500

"""

# revision identifiers, used by Alembic.
revision = '1c915a042c5f'
down_revision = '35e5c528d70f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published_at')
    ### end Alembic commands ###
