"""Add is approved to ApprovementLog model.

Revision ID: d2193474b94
Revises: 45bfa3ae770c
Create Date: 2014-11-20 08:51:23.115999

"""

# revision identifiers, used by Alembic.
revision = 'd2193474b94'
down_revision = '45bfa3ae770c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvement_log', sa.Column('is_approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvement_log', 'is_approved')
    ### end Alembic commands ###
