"""Add show order to BlogKind

Revision ID: 22d1bd4d3452
Revises: 31d0346dd3bf
Create Date: 2014-11-29 10:25:30.212037

"""

# revision identifiers, used by Alembic.
revision = '22d1bd4d3452'
down_revision = '31d0346dd3bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_kind', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('blog_kind', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('blog_kind', sa.Column('show_order', sa.Integer(), nullable=True))
    op.add_column('kind', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kind', 'created_at')
    op.drop_column('blog_kind', 'show_order')
    op.drop_column('blog_kind', 'id')
    op.drop_column('blog_kind', 'created_at')
    ### end Alembic commands ###
