"""Add since to Blog model.

Revision ID: 23e406f6c81b
Revises: 402197a0cb49
Create Date: 2014-11-19 22:33:28.182421

"""

# revision identifiers, used by Alembic.
revision = '23e406f6c81b'
down_revision = '402197a0cb49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('since', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'since')
    ### end Alembic commands ###
