"""Add subtitle to Blog.

Revision ID: cebfc404b8f
Revises: a48ac5425f5
Create Date: 2014-11-02 18:31:42.555121

"""

# revision identifiers, used by Alembic.
revision = 'cebfc404b8f'
down_revision = 'a48ac5425f5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('subtitle', sa.String(length=100), nullable=True))
    op.add_column('blog', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('blog', 'name')
    op.drop_constraint(u'name', 'blog', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'name', 'blog', ['name'])
    op.add_column('blog', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('blog', 'title')
    op.drop_column('blog', 'subtitle')
    ### end Alembic commands ###
