"""Rm RecommendPost model.

Revision ID: 46b93a07c5cc
Revises: 3687ce6a0924
Create Date: 2014-11-26 14:49:15.451771

"""

# revision identifiers, used by Alembic.
revision = '46b93a07c5cc'
down_revision = '3687ce6a0924'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommend_post')
    op.add_column('post', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('recommend', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'recommend')
    op.drop_column('post', 'clicks')
    op.create_table('recommend_post',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], [u'post.id'], name=u'recommend_post_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
