"""Add is_duplicate to Post

Revision ID: 402197a0cb49
Revises: 485fe1a79c3a
Create Date: 2014-11-18 09:55:05.126443

"""

# revision identifiers, used by Alembic.
revision = '402197a0cb49'
down_revision = '485fe1a79c3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_duplicate')
    ### end Alembic commands ###
