"""Add show_order to Kind.

Revision ID: 31d0346dd3bf
Revises: 5785f8ec386
Create Date: 2014-11-28 21:42:19.944649

"""

# revision identifiers, used by Alembic.
revision = '31d0346dd3bf'
down_revision = '5785f8ec386'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kind', sa.Column('show_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kind', 'show_order')
    ### end Alembic commands ###
