"""Add kind_id to Blog.

Revision ID: 2b9daee1ee63
Revises: edc160b5335
Create Date: 2014-11-28 19:31:29.723726

"""

# revision identifiers, used by Alembic.
revision = '2b9daee1ee63'
down_revision = 'edc160b5335'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('kind_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'kind_id')
    ### end Alembic commands ###
