"""Rm pub at from post

Revision ID: 32f47fdf423d
Revises: 9b7feb88ac6
Create Date: 2014-11-13 17:27:43.484603

"""

# revision identifiers, used by Alembic.
revision = '32f47fdf423d'
down_revision = '9b7feb88ac6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pub_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pub_at', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
