"""Update blog.

Revision ID: 4da6f7fc0881
Revises: 2a5b5f32c9ee
Create Date: 2014-11-21 20:20:21.748768

"""

# revision identifiers, used by Alembic.
revision = '4da6f7fc0881'
down_revision = '2a5b5f32c9ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('for_special_purpose', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'for_special_purpose')
    ### end Alembic commands ###
