"""update blog model.

Revision ID: 2faf57d04bf7
Revises: 459f81c0aad7
Create Date: 2014-11-02 16:56:16.707840

"""

# revision identifiers, used by Alembic.
revision = '2faf57d04bf7'
down_revision = '459f81c0aad7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('feed_version', sa.String(length=20), nullable=True))
    op.add_column('blog', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'updated_at')
    op.drop_column('blog', 'feed_version')
    ### end Alembic commands ###
