"""Add is protected to Blog.

Revision ID: 2a5b5f32c9ee
Revises: 20892eac89e5
Create Date: 2014-11-20 20:25:37.364385

"""

# revision identifiers, used by Alembic.
revision = '2a5b5f32c9ee'
down_revision = '20892eac89e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_protected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'is_protected')
    ### end Alembic commands ###
