"""Add keywords to blog.

Revision ID: 5223d07f2efe
Revises: 2ba2d5ae54cc
Create Date: 2014-11-28 16:53:23.691112

"""

# revision identifiers, used by Alembic.
revision = '5223d07f2efe'
down_revision = '2ba2d5ae54cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('keywords', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'keywords')
    ### end Alembic commands ###
