"""Rm last status from blog model.

Revision ID: 362dcae1d3d
Revises: 32f47fdf423d
Create Date: 2014-11-14 21:32:00.690477

"""

# revision identifiers, used by Alembic.
revision = '362dcae1d3d'
down_revision = '32f47fdf423d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'last_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('last_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
