"""Rename is_duplicate to hide.

Revision ID: 1888d7240e64
Revises: 4970efabc64a
Create Date: 2014-11-26 15:05:42.867930

"""

# revision identifiers, used by Alembic.
revision = '1888d7240e64'
down_revision = '4970efabc64a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'is_duplicate', new_column_name="hide",
                    type_=mysql.TINYINT(display_width=1))
    ### end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
