"""Rm unique id.

Revision ID: 426ea81bb3c2
Revises: 2fcd12bece1d
Create Date: 2014-11-15 13:31:00.488735

"""

# revision identifiers, used by Alembic.
revision = '426ea81bb3c2'
down_revision = '2fcd12bece1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'unique_id')
    op.drop_column('post', 'unique_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('unique_id', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('blog', sa.Column('unique_id', mysql.VARCHAR(length=200), nullable=True))
    ### end Alembic commands ###
