"""Add is admin to User.

Revision ID: 4a323d946bda
Revises: d2193474b94
Create Date: 2014-11-20 09:06:57.540846

"""

# revision identifiers, used by Alembic.
revision = '4a323d946bda'
down_revision = 'd2193474b94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
