"""Add unique_id to Blog and Post model.

Revision ID: a48ac5425f5
Revises: 2faf57d04bf7
Create Date: 2014-11-02 18:03:08.959009

"""

# revision identifiers, used by Alembic.
revision = 'a48ac5425f5'
down_revision = '2faf57d04bf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('unique_id', sa.String(length=200), nullable=True))
    op.add_column('post', sa.Column('unique_id', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'unique_id')
    op.drop_column('blog', 'unique_id')
    ### end Alembic commands ###
