"""Add IP to ApprovementLog.

Revision ID: 2c20d7f67551
Revises: 50c7b3046a29
Create Date: 2014-12-05 14:29:28.977434

"""

# revision identifiers, used by Alembic.
revision = '2c20d7f67551'
down_revision = '50c7b3046a29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvement_log', sa.Column('ip', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvement_log', 'ip')
    ### end Alembic commands ###
