"""Add is approved to blog

Revision ID: 2b2a56326a8d
Revises: 426ea81bb3c2
Create Date: 2014-11-15 19:12:34.631061

"""

# revision identifiers, used by Alembic.
revision = '2b2a56326a8d'
down_revision = '426ea81bb3c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'is_approved')
    ### end Alembic commands ###
