"""Add feed status.

Revision ID: 411a55d108af
Revises: 2c20d7f67551
Create Date: 2015-01-22 20:44:54.772309

"""

# revision identifiers, used by Alembic.
revision = '411a55d108af'
down_revision = '2c20d7f67551'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('feed_status', sa.Integer(), nullable=True))
    op.drop_column('blog', 'bad_feed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('bad_feed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('blog', 'feed_status')
    ### end Alembic commands ###
