"""Add UserCollectPost

Revision ID: 2bab6c129a79
Revises: 8f70b7a8ac
Create Date: 2015-03-22 23:49:29.224144

"""

# revision identifiers, used by Alembic.
revision = '2bab6c129a79'
down_revision = '8f70b7a8ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_collect_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collect_post')
    ### end Alembic commands ###
