"""Update post.

Revision ID: 8f70b7a8ac
Revises: 43489c957f9e
Create Date: 2015-02-07 17:08:30.114340

"""

# revision identifiers, used by Alembic.
revision = '8f70b7a8ac'
down_revision = '43489c957f9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'published_at_exceed', type_=sa.Boolean(), existing_type=sa.DateTime())
    op.alter_column('post', 'updated_at_exceed', type_=sa.Boolean(), existing_type=sa.DateTime())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
