"""Update user.

Revision ID: 32a8a834e556
Revises: 387766c87f76
Create Date: 2015-01-25 18:29:44.254312

"""

# revision identifiers, used by Alembic.
revision = '32a8a834e556'
down_revision = '387766c87f76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_read_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_read_at')
    ### end Alembic commands ###
