"""Add unread to UserReadPost.

Revision ID: 472561a202f0
Revises: 30112ee02e96
Create Date: 2015-07-22 12:50:12.062157

"""

# revision identifiers, used by Alembic.
revision = '472561a202f0'
down_revision = '30112ee02e96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_read_post', sa.Column('unread', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_read_post', 'unread')
    ### end Alembic commands ###
