"""Update post.

Revision ID: 43489c957f9e
Revises: 141dc3278681
Create Date: 2015-02-07 17:00:34.921137

"""

# revision identifiers, used by Alembic.
revision = '43489c957f9e'
down_revision = '141dc3278681'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published_at_exceed', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_at_exceed', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated_at_exceed')
    op.drop_column('post', 'published_at_exceed')
    ### end Alembic commands ###
