"""Add is_active and token to User.

Revision ID: 141dc3278681
Revises: 32a8a834e556
Create Date: 2015-01-25 19:34:29.176708

"""

# revision identifiers, used by Alembic.
revision = '141dc3278681'
down_revision = '32a8a834e556'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.drop_column('user', 'is_active')
    ### end Alembic commands ###
